eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8761/eureka/
spring:
  application:
    name: zuul-gateway
server:
  port: 5555
zuul:
  routes:
    api-a :
      path: /api-a/**
      url: http://localhost:8080/